// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpoxBiSmcJ3SpxXRs95ZLvqDMGZDo6Sh8',
    appId: '1:623834511492:web:b8748fdcf2098d46ac6ad1',
    messagingSenderId: '623834511492',
    projectId: 'med-aid-462319',
    authDomain: 'med-aid-462319.firebaseapp.com',
    storageBucket: 'med-aid-462319.firebasestorage.app',
    measurementId: 'G-DGT2ZW0HEH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRz7vl54dXIubQDoNQT_Bm33IsknDsKc',
    appId: '1:623834511492:ios:9ec12abace2264f6ac6ad1',
    messagingSenderId: '623834511492',
    projectId: 'med-aid-462319',
    storageBucket: 'med-aid-462319.firebasestorage.app',
    iosBundleId: 'com.example.medAid',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRz7vl54dXIubQDoNQT_Bm33IsknDsKc',
    appId: '1:623834511492:ios:9ec12abace2264f6ac6ad1',
    messagingSenderId: '623834511492',
    projectId: 'med-aid-462319',
    storageBucket: 'med-aid-462319.firebasestorage.app',
    iosBundleId: 'com.example.medAid',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3WWvYd2WHm_1Pxvja7GvvkMxiWN5FjI',
    appId: '1:623834511492:android:d425173a89ee4d08ac6ad1',
    messagingSenderId: '623834511492',
    projectId: 'med-aid-462319',
    storageBucket: 'med-aid-462319.firebasestorage.app',
  );

}